version: '3.8'

services:
  backend:
    build:
      context: ./SportFastBackend/www/SportFastBackend
    volumes:
      - ./SportFastBackend/www/SportFastBackend:/var/www
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_DATABASE=sportfast
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - db

  frontend:
    build:
      context: ./SportFastFrontend/sportfastFrontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./SportFastFrontend/sportfastFrontend/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/sportfast.zapto.org:/etc/letsencrypt/live/sportfast.zapto.org:ro
      - /etc/letsencrypt/archive/sportfast.zapto.org:/etc/letsencrypt/archive/sportfast.zapto.org:ro
      - /etc/letsencrypt/privkey.pem:/etc/letsencrypt/privkey.pem:ro
    depends_on:
      - backend

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: sportfast
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    depends_on:
      - db

volumes:
  db_data: