version: '3.8'

services:
  backend:
    build:
      context: ./SportFastBackend/www/SportFastBackend
    volumes:
      - ./SportFastBackend/www/SportFastBackend:/var/www
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_DATABASE=sportfast
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - db

  frontend:
    build:
      context: ./SportFastFrontend/sportfastFrontend
    ports:
      - "4200:80"
    depends_on:
      - backend

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: sportfast
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    depends_on:
      - db

volumes:
  db_data: